version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: html-entities
    versions:
    - 2.1.0
    - 2.1.1
    - 2.3.1
  - dependency-name: miniget
    versions:
    - 4.1.0
